import React, { createContext, useContext, useState, useEffect } from 'react';
import { Language } from '../types';
import { useFirebase } from './FirebaseProvider';

type Translations = Record<string, string>;

const translations: Record<Language, Translations> = {
  ms: {
    'app.name': 'AIHMs Guardian',
    'app.tagline': 'Sistem Pemantauan Kesihatan Warga Emas Berasaskan AI.',
    'app.loading': 'Memuatkan AIHMs',
    'auth.login': 'Log Masuk',
    'auth.register': 'Daftar Akaun',
    'auth.email': 'Emel',
    'auth.password': 'Kata Laluan',
    'auth.username': 'Nama Pengguna',
    'auth.role': 'Peranan',
    'auth.no_account': 'Tiada akaun? Daftar sekarang',
    'auth.have_account': 'Sudah ada akaun? Log masuk',
    'auth.login_btn': 'Log Masuk',
    'auth.register_btn': 'Daftar',
    'auth.invalid_email': 'Emel tidak sah',
    'auth.email_in_use': 'Emel ini telah digunakan oleh akaun lain.',
    'auth.invalid_credentials': 'Emel atau kata laluan tidak sah. Sila cuba lagi.',
    'auth.weak_password': 'Kata laluan terlalu lemah (min. 6 aksara)',
    'auth.required': 'Ruangan ini diperlukan',
    'auth.access_code': 'Kod Akses',
    'auth.invalid_code': 'Kod akses tidak sah',
    'auth.gender': 'Jantina',
    'auth.male': 'Lelaki',
    'auth.female': 'Perempuan',
    'auth.other': 'Lain-lain',
    'auth.blood_type': 'Kumpulan Darah',
    'auth.address': 'Alamat Rumah',
    'auth.dob': 'Tarikh Lahir',
    'auth.conditions': 'Keadaan Sedia Ada / Penyakit Kronik',
    'auth.medications': 'Ubat-ubatan Semasa',
    'auth.ic_number': 'Nombor Kad Pengenalan (IC)',
    'auth.full_name_ic': 'Nama seperti dalam IC',
    'auth.phone_number': 'Nombor Telefon',
    'auth.relationship': 'Hubungan dengan Pesakit',
    'auth.family': 'Ahli Keluarga',
    'auth.professional': 'Penjaga Profesional',
    'auth.friend': 'Rakan',
    'auth.agency_id': 'ID Agensi (Jika ada)',
    'auth.license_number': 'Nombor Lesen (ID Lembaga Perubatan)',
    'auth.signature': 'Tandatangan Digital (Taip Nama Penuh)',
    'auth.logout': 'Log Keluar',
    'auth.google_login': 'Teruskan dengan Google',
    'nav.dashboard': 'Utama',
    'nav.insights': 'Wawasan',
    'nav.chat': 'Sembang',
    'nav.calendar': 'Kalendar',
    'nav.community': 'Komuniti',
    'nav.health_circle': 'Bulatan Kesihatan',
    'nav.patient_profile': 'Profil Pesakit',
    'nav.health_circle_caregiver': 'Profil Pesakit',
    'nav.health_circle_patient': 'Rangkaian Penjagaan',
    'nav.settings': 'Tetapan',
    'nav.admin': 'Admin',
    'dashboard.greeting_morning': 'Selamat Pagi',
    'dashboard.greeting_afternoon': 'Selamat Tengah Hari',
    'dashboard.greeting_evening': 'Selamat Petang',
    'dashboard.tagline': 'Penjaga Bercahaya',
    'dashboard.health_priority': 'Kesihatan anda adalah keutamaan kami. Berikut adalah gambaran klinikal anda hari ini.',
    'dashboard.caregiver_view': 'Anda sedang melihat papan pemuka kesihatan {name}.',
    'dashboard.vitals_title': 'Metrik Vitaliti',
    'dashboard.add_log': 'Tambah Log',
    'dashboard.log_vitals': 'Log Vital',
    'dashboard.history_title': 'Sejarah Klinikal',
    'onboarding.welcome': 'Selamat Datang ke AIHMs',
    'onboarding.welcome_desc': 'Mari kami tunjukkan cara menggunakan aplikasi ini untuk memantau kesihatan anda dengan lebih baik.',
    'onboarding.role_title': 'Pilih Peranan Anda',
    'onboarding.role_desc': 'Adakah anda seorang pesakit yang ingin memantau kesihatan, atau penjaga yang membantu orang lain?',
    'onboarding.vitals_title': 'Log Data Kesihatan',
    'onboarding.vitals_desc': 'Anda boleh merekodkan berat badan, kadar jantung, dan langkah harian anda di sini untuk pemantauan AI.',
    'onboarding.analysis_title': 'Lihat Analisis AI',
    'onboarding.analysis_desc': 'AI kami akan menganalisis data anda dan memberikan rumusan kesihatan yang mudah difahami.',
    'onboarding.chat_title': 'Bantuan Chat AI',
    'onboarding.chat_desc': 'Ada soalan tentang kesihatan? Tanya sahaja pembantu AI kami pada bila-bila masa.',
    'onboarding.patient': 'Pesakit',
    'onboarding.caregiver': 'Penjaga',
    'onboarding.next': 'Seterusnya',
    'onboarding.start': 'Mula Sekarang',
    'onboarding.tutorial': 'Tutorial Interaktif',
    'chat.header_tagline': 'Pembantu Agensi',
    'chat.header_title': 'Sembang Kesihatan',
    'chat.header_desc': 'Sila beritahu saya jika anda rasa tidak sihat atau ingin merekod vitals.',
    'chat.placeholder': 'Tanya saya apa-apa...',
    'chat.welcome': 'Selamat datang. Saya asisten AIHMs anda. Sila beritahu saya tentang kesihatan anda.',
    'chat.mic_error': 'Maaf, saya tidak dapat mengakses mikrofon anda. Sila pastikan anda telah membenarkan akses mikrofon di pelayar web anda.',
    'chat.mic_denied': 'Akses mikrofon ditolak. Sila benarkan akses mikrofon untuk menggunakan fungsi suara.',
    'chat.ai_triage_result': 'Keputusan Triaj AI',
    'chat.status': 'Status',
    'chat.zone': 'Zon',
    'chat.action_emergency': 'Kecemasan',
    'chat.action_scheduling': 'Penjadualan',
    'chat.action_community': 'Komuniti',
    'chat.action_none': 'Tiada',
    'insights.header_tagline': 'Kecerdasan Klinikal',
    'insights.header_title': 'Wawasan Kesihatan',
    'insights.header_desc': 'Analisis trend geriatrik dikuasakan oleh protokol perubatan Malaysia.',
    'insights.health_score': 'Skor Kesihatan',
    'insights.ai_assessment': 'Penilaian AI',
    'insights.alert_title': 'Amaran Kesihatan Proaktif',
    'insights.summary_title': 'Ringkasan Klinikal',
    'insights.generating': 'Analisis sedang dijana...',
    'insights.trend_report': 'Laporan Trend',
    'insights.verified': 'Disahkan mengikut CPG Malaysia.',
    'insights.ai_assistance': 'Asisten Kesihatan AI',
    'insights.view_all': 'Lihat Semua',
    'insights.systolic': 'Sistolik',
    'insights.bp_trend': 'Trend Tekanan Darah',
    'insights.heart_rate': 'Kadar Jantung',
    'insights.activity': 'Aktiviti Harian (Langkah)',
    'insights.sleep': 'Corak Tidur (Jam)',
    'insights.mood': 'Mood & Kesejahteraan Emosi',
    'insights.recommendations': 'Cadangan',
    'insights.status_stable': 'Stabil',
    'insights.status_normal': 'Normal',
    'insights.status_improving': 'Meningkat',
    'insights.status_restorative': 'Memulihkan',
    'insights.status_positive': 'Positif',
    'insights.rec_desc': 'Tindakan klinikal yang disyorkan berdasarkan bacaan log pesakit dan analisis AIHMs.',
    'insights.live_updates': 'Data Masa Nyata',
    'insights.calculated_score': 'Status Kesihatan',
    'calendar.header_tagline': 'Pengurusan Masa',
    'calendar.header_title': 'Jadual Kesihatan',
    'calendar.header_desc': 'Urus temujanji perubatan dan aktiviti komuniti anda dengan tepat.',
    'calendar.ai_suggestion': 'Cadangan AI',
    'calendar.ai_suggestion_desc': 'Berdasarkan bacaan log pesakit baru-baru ini, saya mencadangkan susulan dengan Dr. Lim pada {date}. Adakah anda ingin mengesahkan?',
    'calendar.placeholder_title': 'cth., Susulan Dr. Lim',
    'calendar.placeholder_location': 'cth., Hospital Kuala Lumpur',
    'calendar.upcoming': 'Acara Akan Datang',
    'calendar.confirm': 'Sahkan',
    'calendar.reschedule': 'Jadual Semula',
    'calendar.add_title': 'Temujanji Baru',
    'calendar.event_title': 'Tajuk Acara',
    'calendar.location': 'Lokasi (Pilihan)',
    'calendar.date': 'Tarikh',
    'calendar.time': 'Masa',
    'calendar.category': 'Kategori',
    'calendar.reminders': 'Aktifkan Peringatan',
    'calendar.reminders_desc': 'Beritahu saya 15 minit sebelum',
    'calendar.cancel': 'Batal',
    'calendar.schedule': 'Jadualkan',
    'calendar.confirm_success': 'Cadangan AI disahkan!',
    'calendar.no_events_on_day': 'Tiada acara hari ini.',
    'calendar.clear_selection': 'Padam',
    'calendar.delete_title': 'Padam Temujanji?',
    'calendar.delete_desc': 'Adakah anda pasti ingin memadam temujanji "{title}"? Tindakan ini tidak boleh diubah.',
    'calendar.delete_confirm': 'Padam',
    'calendar.cat_checkup': 'Pemeriksaan Tahunan',
    'calendar.cat_followup': 'Susulan',
    'calendar.cat_specialist': 'Pakar',
    'calendar.cat_other': 'Lain-lain',
    'calendar.view_month': 'Bulan',
    'calendar.view_week': 'Minggu',
    'calendar.view_day': 'Hari',
    'calendar.hospitals_title': 'Hospital Berdekatan',
    'calendar.hospitals_desc': 'Berdasarkan lokasi anda, ini adalah fasiliti kesihatan terdekat.',
    'calendar.nearest': 'Terdekat',
    'calendar.get_location': 'Dapatkan Lokasi',
    'community.header_tagline': 'Hab Sosial',
    'community.header_title': 'Nadi Komuniti',
    'community.header_desc': 'Menghubungkan warga emas Malaysia untuk gaya hidup yang lebih sihat, aktif, dan bermaruah.',
    'community.create_circle': 'Cipta Bulatan',
    'community.create_post': 'Cipta Hantaran',
    'community.who_to_follow': 'Siapa untuk diikuti',
    'community.recommended_circles': 'Bulatan Disyorkan',
    'community.follow': 'Ikut',
    'community.following': 'Mengikuti',
    'community.join': 'Sertai',
    'community.joined': 'Disertai',
    'community.rsvp_count': '{count} orang akan hadir',
    'community.share_success': 'Pautan dikongsi!',
    'community.no_recommendations': 'Tiada cadangan buat masa ini',
    'community.search_placeholder': 'Cari kiriman, ahli, atau jenis...',
    'community.all_feed': 'Semua Kiriman',
    'community.no_posts': 'Tiada kiriman komuniti lagi. Jadilah yang pertama untuk berkongsi!',
    'community.share': 'Kongsi',
    'community.copied': 'Disalin',
    'community.join_event': 'Sertai Acara',
    'community.event_calendar_title': 'Acara Komuniti: {title}',
    'community.event_calendar_notes': 'Lokasi acara: {location}. Kandungan: {content}',
    'community.delete_post_confirm': 'Adakah anda pasti ingin memadam kiriman ini?',
    'community.pulse_title': 'Nadi Komuniti',
    'community.active_circles': 'Bulatan Aktif',
    'community.members': 'ahli',
    'community.joined_btn': 'Telah Disertai',
    'community.join_btn': 'Sertai',
    'community.no_posts_search': 'Tiada kiriman ditemui untuk "{query}"',
    'community.no_posts_default': 'Tiada kiriman komuniti lagi. Jadilah yang pertama untuk berkongsi!',
    'community.no_circles': 'Tiada bulatan aktif lagi. Jadilah yang pertama untuk memulakannya!',
    'community.circle_tasks': 'Tugasan Bulatan',
    'community.spirit_title': 'Semangat Komuniti',
    'community.spirit_energetic': 'Komuniti kami berasa Bertenaga hari ini!',
    'community.spirit_progress': '{name} adalah {progress}% ke arah matlamatnya!',
    'community.spirit_quiet': 'Senyap',
    'community.spirit_vibrant': 'Bertenaga',
    'community.spirit_starting': 'Bermula',
    'community.spirit_goal_reached': 'Matlamat Tercapai',
    'community.member_status': 'Ahli Komuniti',
    'community.edit_profile': 'Kemaskini Profil',
    'community.my_posts': 'Kiriman Saya',
    'community.leaders_peers': 'Pemimpin & Rakan Sebaya',
    'community.leader': 'Pemimpin Komuniti',
    'community.contributor': 'Penyumbang Utama',
    'community.active_member': 'Ahli Aktif',
    'community.view_profile': 'Lihat Profil',
    'community.share_something': 'Kongsi Sesuatu',
    'community.post_type': 'Jenis Kiriman',
    'community.post_type_event': 'Acara',
    'community.post_type_health_tip': 'Tip Kesihatan',
    'community.post_type_question': 'Soalan',
    'community.post_type_update': 'Kemaskini',
    'community.posting_to': 'Kongsi Ke',
    'community.title': 'Tajuk',
    'community.location': 'Lokasi',
    'community.event_date': 'Tarikh Acara',
    'community.content': 'Kandungan',
    'community.sending': 'Menghantar...',
    'community.send_post': 'Hantar Kiriman',
    'community.create_circle_title': 'Cipta Bulatan Baru',
    'community.circle_name': 'Nama Bulatan',
    'community.description': 'Penerangan',
    'community.choose_icon': 'Pilih Ikon',
    'community.creating': 'Mencipta...',
    'community.create_btn': 'Cipta Bulatan',
    'community.following_btn': 'Mengikuti',
    'community.follow_btn': 'Ikuti',
    'community.message': 'Mesej',
    'community.posts_count': 'Kiriman',
    'community.followers_count': 'Pengikut',
    'community.following_count': 'Mengikuti',
    'community.recent_activity': 'Aktiviti Terkini',
    'community.no_posts_user': 'Tiada kiriman lagi.',
    'community.no_followers': 'Tiada pengikut lagi.',
    'community.no_following': 'Tiada yang diikuti lagi.',
    'community.delete_post_tooltip': 'Padam Kiriman',
    'community.trending': 'Trending',
    'community.quote': '"Komuniti adalah tempat di mana perjalanan kesihatan anda menjadi kemenangan bersama. Bersama-sama, kita berkembang dan menua dengan bermaruah."',
    'community.member': 'Ahli',
    'community.circle_name_placeholder': 'Contoh: Yoga Pagi',
    'community.circle_desc_placeholder': 'Apakah tujuan bulatan ini?',
    'community.bio': 'Bio',
    'community.bio_placeholder': 'Beritahu komuniti tentang diri anda...',
    'community.default_bio': 'Berdedikasi untuk menjalani gaya hidup sihat dan aktif. Meminati berkebun komuniti, berjalan pagi, dan berkongsi resipi berkhasiat dengan rakan-rakan.',
    'community.likes': 'Suka',
    'community.bookmark': 'Simpan',
    'community.unbookmark': 'Batal Simpan',
    'community.active_bookmarks': 'Simpanan Aktif',
    'community.saved_items': 'Item Disimpan',
    'community.comment': 'Komen',
    'community.delete_post_title': 'Padam Hantaran',
    'community.notify_caregiver': 'Maklumkan Penjaga',
    'community.report': 'Laporkan',
    'community.report_success': 'Hantaran telah dilaporkan kepada moderator.',
    'community.comments_title': 'Perbincangan',
    'community.responses': 'Maklum balas',
    'community.no_comments': 'Jadilah yang pertama menyertai perbincangan!',
    'community.write_comment': 'Tambah komen...',
    'health_circle.header_tagline': 'Rangkaian Penjagaan',
    'health_circle.header_title': 'Bulatan Kesihatan',
    'health_circle.header_desc': 'Hubungi penjaga yang dipercayai untuk sentiasa mendapat maklumat tentang kesejahteraan anda.',
    'health_circle.privacy_title': 'Privasi & Keizinan',
    'health_circle.call': 'Panggilan Suara',
    'health_circle.video_call': 'Panggilan Video',
    'health_circle.chat': 'Sembang Terus',
    'health_circle.coming_soon': 'Fungsi ini akan tersedia tidak lama lagi.',
    'health_circle.my_caregivers': 'Penjaga Saya',
    'health_circle.linked_patients': 'Pesakit Di bawah Jagaan',
    'health_circle.privacy_desc': 'Data kesihatan anda hanya dikongsi dengan penjaga yang dipautkan secara sah melalui ID Profil anda.',
    'health_circle.no_contacts': 'Tiada kenalan ditambah lagi.',
    'health_circle.add_desc': 'Tambah sehingga 3 orang ahli keluarga atau penjaga.',
    'health_circle.emergency_alerts': 'Amaran Kecemasan',
    'health_circle.weekly_summary': 'Ringkasan Mingguan',
    'health_circle.trusted_contact': 'Kenalan Dipercayai',
    'health_circle.add_contact': 'Tambah Kenalan',
    'health_circle.full_name': 'Nama Penuh',
    'health_circle.relation': 'Hubungan',
    'health_circle.email': 'Emel',
    'health_circle.phone': 'No. Telefon',
    'health_circle.saving': 'Menyimpan...',
    'health_circle.limit_alert': 'Anda hanya boleh menambah sehingga 3 kenalan dipercayai.',
    'health_circle.delete_confirm': 'Adakah anda pasti ingin memadam kenalan ini?',
    'drawer.emergency_title': 'Tindakan Kecemasan',
    'drawer.sos_button': 'Cetuskan SOS',
    'drawer.sos_desc': 'Amaran semua kenalan dipercayai',
    'drawer.sos_confirm_title': 'Sahkan SOS',
    'drawer.sos_confirm_desc': 'Ini akan segera memaklumkan penjaga dan kenalan kecemasan anda tentang lokasi semasa anda.',
    'drawer.sos_confirm_btn': 'Ya, Cetuskan SOS',
    'drawer.sos_success': 'SOS Diaktifkan',
    'drawer.sos_success_desc': 'Kenalan dipercayai anda telah dimaklumkan. Bantuan sedang dalam perjalanan.',
    'drawer.sending': 'Menghantar Amaran...',
    'drawer.sending_desc': 'Mengesan peranti dan menghubungi rangkaian kecemasan. Sila bertenang.',
    'drawer.navigation_title': 'Menu Utama',
    'drawer.support_title': 'Sokongan & Info',
    'drawer.help_center': 'Pusat Bantuan',
    'drawer.about': 'Mengenai AIHMs',
    'settings.header_tagline': 'Pusat Kawalan',
    'settings.header_desc': 'Konfigurasikan pengalaman AIHMs, privasi, dan peranti yang disambungkan.',
    'settings.location_sharing_active': 'Perkongsian Lokasi Aktif',
    'settings.role_caregiver': 'Penjaga',
    'settings.role_patient': 'Pesakit',
    'settings.role_leader': 'Pemimpin',
    'settings.role_contributor': 'Penyumbang',
    'settings.role_member': 'Ahli',
    'settings.active_account': 'Akaun Aktif',
    'settings.theme_desc': 'Sesuaikan warna aplikasi mengikut keselesaan anda.',
    'settings.language_desc': 'Pilih bahasa pilihan anda untuk aplikasi ini.',
    'theme.emerald': 'Hutan Zamrud',
    'theme.sapphire': 'Nilam Diraja',
    'theme.harvest': 'Hasil Emas',
    'theme.lavender': 'Lavender Tenang',
    'settings.link_patient_title': 'Pautkan Pesakit',
    'settings.link_patient_desc': 'Masukkan ID Pesakit untuk memantau kesihatan mereka.',
    'settings.patient_id_label': 'ID Pesakit',
    'settings.patient_id_placeholder': 'Masukkan ID Pesakit',
    'settings.patient_id_hint': 'ID ini boleh didapati dalam profil pesakit.',
    'settings.linking': 'Memautkan...',
    'settings.link': 'Pautkan',
    'settings.update_profile_title': 'Kemaskini Profil',
    'settings.update_profile_desc': 'Kemaskini maklumat peribadi anda di sini.',
    'settings.display_name_label': 'Nama Paparan',
    'settings.display_name_placeholder': 'Masukkan nama anda',
    'settings.photo_url_label': 'URL Gambar Profil',
    'settings.regenerate': 'Regenerasi',
    'settings.saving': 'Menyimpan...',
    'settings.save': 'Simpan',
    'settings.change_role_title': 'Tukar Peranan',
    'settings.change_role_desc': 'Pilih peranan anda dalam AIHMs.',
    'settings.role_patient_desc': 'Pantau kesihatan anda dan terima peringatan.',
    'settings.role_caregiver_desc': 'Pantau kesihatan ahli keluarga atau pesakit anda.',
    'settings.privacy_controls_title': 'Kawalan Privasi',
    'settings.privacy_controls_desc': 'Urus data dan kebenaran perkongsian anda.',
    'settings.location_sharing_label': 'Perkongsian Lokasi',
    'settings.location_sharing_hint': 'Benarkan AIHMs berkongsi lokasi anda dengan penjaga semasa kecemasan.',
    'settings.data_sharing_label': 'Perkongsian Data Penjaga',
    'settings.data_sharing_hint': 'Penjaga yang dipautkan boleh melihat log kesihatan dan data vital anda.',
    'settings.third_party_label': 'Perkhidmatan Pihak Ketiga',
    'settings.third_party_hint': 'Urus sambungan ke peranti seperti Fitbit dan Google Fit.',
    'dashboard.wearable_connected': 'Peranti Dipakai Disambung',
    'dashboard.last_synced': 'Terakhir disinkronkan',
    'dashboard.never': 'Tidak pernah',
    'dashboard.clarity_title': 'Kejelasan Harian',
    'dashboard.clarity_desc': 'Jangan lupa ubat pagi anda dengan sarapan. Kadar jantung anda stabil.',
    'dashboard.medication_logged': 'Ubat Direkodkan',
    'dashboard.triage_red_label': 'Kecemasan',
    'dashboard.triage_red_desc': 'Perhatian perubatan segera diperlukan.',
    'dashboard.triage_yellow_label': 'Segera',
    'dashboard.triage_yellow_desc': 'Sila pantau dengan teliti dan rujuk jururawat.',
    'dashboard.triage_green_label': 'Stabil',
    'dashboard.triage_green_desc': 'Vital berada dalam julat yang boleh diterima.',
    'dashboard.triage_none_label': 'Tiada Data',
    'dashboard.triage_none_desc': 'Log vital anda untuk melihat status.',
    'dashboard.goals_title': 'Gelang Matlamat',
    'dashboard.daily_steps': 'Langkah Harian',
    'dashboard.log_vitals_desc': 'Kemaskini rekod kesihatan anda secara manual',
    'dashboard.monitor_closely': 'Pantau Dengan Teliti',
    'dashboard.save_record': 'Simpan Rekod Kesihatan',
    'dashboard.save_success': 'Rekod kesihatan telah berjaya disimpan.',
    'dashboard.full_archive': 'Arkib Lengkap',
    'dashboard.no_records': 'Tiada rekod dijumpai. Mulakan perjalanan anda hari ini.',
    'history.archive_desc': 'Rekod sejarah lengkap log kesihatan untuk {target}.',
    'history.total_records': 'Jumlah Rekod',
    'history.search_logs': 'Cari nota, status...',
    'history.all_zones': 'Semua Status',
    'history.delete_title': 'Padam Rekod?',
    'history.delete_desc': 'Ini akan memadam entri kesihatan ini secara kekal dari log sejarah. Tindakan ini tidak boleh diubah.',
    'history.no_records_found': 'Tiada Rekod Dijumpai',
    'history.adjust_filters': 'Cuba selaraskan penapis atau carian anda untuk mencari log tertentu.',
    'dashboard.zone_red': 'Zon Merah',
    'dashboard.zone_yellow': 'Zon Kuning',
    'dashboard.zone_green': 'Zon Hijau',
    'metrics.activity': 'Aktiviti',
    'metrics.steps': 'langkah',
    'metrics.heart_rate': 'Kadar Jantung',
    'metrics.weight': 'Berat',
    'metrics.blood_pressure': 'Tekanan Darah',
    'metrics.sleep': 'Tidur',
    'metrics.hours': 'Jam',
    'metrics.mood': 'Mood',
    'metrics.heart': 'Jantung',
    'metrics.bp': 'TD',
    'metrics.kg': 'kg',
    'metrics.bpm': 'bpm',
    'metrics.h': 'jam',
    'mood.title': 'Mood',
    'mood.poor': 'Teruk',
    'mood.fair': 'Sederhana',
    'mood.neutral': 'Neutral',
    'mood.good': 'Baik',
    'mood.excellent': 'Cemerlang',
    'settings.title': 'Tetapan Aplikasi',
    'settings.language': 'Bahasa',
    'settings.theme': 'Tema Aplikasi',
    'settings.logout': 'Log Keluar dari AIHMs',
    'settings.profile': 'Profil',
    'settings.role': 'Peranan',
    'settings.privacy': 'Kawalan Privasi',
    'settings.care_network': 'Rangkaian Penjagaan',
    'settings.health_services': 'Perkhidmatan Kesihatan',
    'settings.preferences': 'Keutamaan',
    'settings.select_language': 'Pilih Bahasa',
    'settings.select_theme': 'Pilih Tema',
    'dashboard.greeting_user_default': 'Tuan/Puan',
    'feedback.title': 'Maklum Balas',
    'feedback.desc': 'Bagaimana pengalaman anda menggunakan AIHMs? Sila kongsikan cadangan atau masalah yang anda hadapi.',
    'feedback.label': 'Mesej Anda',
    'feedback.placeholder': 'Tulis maklum balas anda di sini...',
    'feedback.submit': 'Hantar Maklum Balas',
    'feedback.submitting': 'Menghantar...',
    'feedback.thanks': 'Terima Kasih!',
    'feedback.thanks_desc': 'Maklum balas anda telah dihantar. Kami menghargai sokongan anda.',
    'health_circle.add_up_to': 'Tambah sehingga 3 orang ahli keluarga atau penjaga.',
    'health_circle.relationship': 'Hubungan',
    'health_circle.placeholder_email': 'ahmad@email.com',
    'health_circle.placeholder_phone': '+60123456789',
    'health_circle.add_placeholder_name': 'Contoh: Ahmad Bin Ali',
    'health_circle.add_placeholder_relation': 'Contoh: Anak Lelaki / Penjaga',
    'health_circle.enable_alerts': 'Aktifkan Amaran',
    'health_circle.enable_reports': 'Aktifkan Laporan',
    'health_circle.cancel': 'Batal',
    'health_circle.add': 'Tambah',
    'notification.reminder_title': 'Peringatan Temujanji: {title}',
    'notification.reminder_body': 'Temujanji anda bermula pada jam {time}.',
    'common.close': 'Tutup',
    'common.view_details': 'Lihat Butiran',
    'common.cancel': 'Batal',
    'common.anonymous': 'Tanpa Nama',
    'common.delete': 'Padam',
    'common.back_to_dashboard': 'Kembali ke Papan Utama',
    'common.you': 'anda',
    'calendar.add_event': 'Tambah Acara',
    'calendar.events': 'Acara',
    'calendar.no_records': 'Tiada rekod',
    'calendar.no_upcoming': 'Tiada acara akan datang',
    'calendar.records': 'Rekod',
    'calendar.records_count': 'rekod',
    'calendar.return_to_today': 'Kembali ke hari ini',
    'chat.start_chat': 'Mula Sembang',
    'dashboard.current_status': 'Status Semasa',
    'dashboard.delete_confirm': 'Adakah anda pasti mahu memadam ini?',
    'dashboard.delete_confirm_title': 'Sahkan Padam',
    'dashboard.log_notes': 'Nota Log',
    'dashboard.metric_desc_prefix': '',
    'dashboard.metric_desc_suffix': '',
    'dashboard.record_details': 'Butiran Rekod',
    'dashboard.within_healthy_range': 'Dalam julat sihat',
    'health_circle.delete_confirm_title': 'Sahkan Padam',
    'settings.add_reminder': 'Tambah Peringatan',
    'chat.ai_extracted_notes': 'AI diekstrak dari sembang: {text}',
    'community.post_type_tip': 'Tip',
    'community.post_type_milestone': 'Pencapaian',
    'settings.section_account': 'Akaun',
    'settings.label_profile': 'Profil',
    'settings.label_role': 'Peranan',
    'settings.label_privacy': 'Privasi',
    'settings.section_care_network': 'Rangkaian Penjagaan',
    'settings.label_link_patient': 'Pautkan Pesakit',
    'settings.status_linked': 'Dipautkan',
    'settings.status_not_linked': 'Tidak Dipautkan',
    'settings.main_caregiver_title': 'Penjaga Utama',
    'settings.main_caregiver_desc': 'Pilih orang utama untuk dihubungi jika berlaku kecemasan.',
    'settings.label_my_caregivers': 'Penjaga Saya',
    'settings.status_none': 'Tiada',
    'settings.section_health_services': 'Perkhidmatan Kesihatan',
    'settings.label_emergency_location': 'Lokasi Kecemasan',
    'settings.status_active': 'Aktif',
    'settings.status_disabled': 'Dinyahaktifkan',
    'settings.label_wearable': 'Integrasi Peranti Pakai',
    'settings.status_syncing': 'Menyinkronkan...',
    'settings.status_fitbit_connected': 'Fitbit Disambung',
    'settings.status_not_connected': 'Tidak Disambung',
    'settings.section_preferences': 'Keutamaan',
    'settings.label_smart_notifications': 'Notifikasi Pintar',
    'settings.notifications_enabled_title': 'Notifikasi Diaktifkan',
    'settings.notifications_enabled_body': 'Anda akan menerima peringatan kesihatan dan amaran.',
    'settings.confirm_role_caregiver': 'Adakah anda pasti ingin menukar peranan kepada Penjaga? Anda akan dapat memantau pesakit yang dipautkan.',
    'settings.confirm_role_patient': 'Adakah anda pasti ingin menukar peranan kepada Pesakit? Anda akan dapat memantau kesihatan anda sendiri.',
    'settings.patient_id_not_found': 'ID Pesakit tidak dijumpai.',
    'settings.not_a_patient': 'ID yang diberikan bukan milik seorang pesakit.',
    'settings.fitbit_connect_error': 'Gagal menyambung ke Fitbit. Sila cuba lagi.',
    'settings.fitbit_sync_success': 'Data Fitbit berjaya disinkronkan!',
    'settings.fitbit_sync_error': 'Gagal menyinkronkan data Fitbit.',
    'settings.synced_from_fitbit': 'Disinkronkan dari Fitbit',
    'settings.clinical_id_title': 'Kad Pengenalan Kesihatan',
    'settings.clinical_id_desc': 'Kad ID maya ini memudahkan perkongsian maklumat klinikal dengan penjaga anda.',
    'settings.view_id_card': 'Lihat Kad ID',
    'settings.copy_id': 'Salin ID',
    'settings.id_copied': 'ID disalin ke papan klip!',
    'settings.blood_type': 'Jenis Darah',
    'settings.invite_token': 'Kod Jemputan',
    'settings.refresh_token': 'Segarkan',
    'settings.expires_in': 'Tamat dalam',
    'settings.no_active_token': 'Tiada kod aktif',
    'settings.generate_now': 'Jana Sekarang',
    'settings.linkage_tip': 'Kongsi kod ini dan ID Pesakit anda dengan penjaga anda untuk menghubungkan akaun.',
    'settings.invite_token_label': 'Kod Jemputan',
    'settings.link_account': 'Hubung Akaun',
    'settings.linkage_help': 'Minta pesakit membuka kad ID profil mereka untuk melihat ID dan kod jemputan sementara.',
    'settings.invalid_token': 'Kod jemputan tidak sah',
    'settings.token_expired': 'Kod jemputan telah tamat tempoh',
    'settings.allergies': 'Alergi',
    'settings.emergency_contact': 'Kecemasan',
    'settings.full_id': 'ID Penuh',
    'wearables.header_tagline': 'Integrasi Peranti',
    'wearables.header_title': 'Hab Peranti Pintar',
    'wearables.header_desc': 'Sambungkan peranti pakai kegemaran anda ke AIHMs untuk pemantauan kesihatan masa nyata yang lancar.',
    'wearables.header_desc_caregiver': 'Menguruskan peranti boleh pakai {name}. Senyegerakkan data kesihatan untuk memantau kesejahteraan mereka.',
    'wearables.connect_fitbit': 'Sambung Fitbit',
    'wearables.connect_apple': 'Sambung Apple Health',
    'wearables.connect_google': 'Sambung Google Fit',
    'wearables.sync_now': 'Sinkron Sekarang',
    'wearables.simulate_sync': 'Simulasi Sinkron (Demo)',
    'wearables.coming_soon': 'Akan Datang untuk Web',
    'wearables.steps_desc': 'Pantau aktiviti harian dan sasaran anda.',
    'wearables.heart_desc': 'Pemantauan kadar jantung rehat masa nyata.',
    'wearables.sleep_desc': 'Analisis pemulihan dan kitaran tidur anda.',
    'community.task_morning_walk': 'Berjalan Pagi Harian',
    'community.task_recipe_share': 'Kongsi Resipi Sihat',
    'community.task_group_chat': 'Sembang Kumpulan Mingguan',
    'language.ms': 'Bahasa Melayu',
    'language.en': 'English',
    'language.zh': 'Mandarin (中文)',
  },
  en: {
    'app.name': 'AIHMs Guardian',
    'app.tagline': 'AI-Powered Geriatric Health Monitoring System.',
    'app.loading': 'Loading AIHMs',
    'auth.login': 'Login',
    'auth.register': 'Register Account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.username': 'Username',
    'auth.role': 'Role',
    'auth.no_account': 'No account? Register now',
    'auth.have_account': 'Already have an account? Login',
    'auth.login_btn': 'Login',
    'auth.register_btn': 'Register',
    'auth.invalid_email': 'Invalid email',
    'auth.email_in_use': 'This email is already in use by another account.',
    'auth.invalid_credentials': 'Invalid email or password. Please try again.',
    'auth.weak_password': 'Password too weak (min. 6 chars)',
    'auth.required': 'This field is required',
    'auth.access_code': 'Access Code',
    'auth.invalid_code': 'Invalid access code',
    'auth.gender': 'Gender',
    'auth.male': 'Male',
    'auth.female': 'Female',
    'auth.other': 'Other',
    'auth.blood_type': 'Blood Type',
    'auth.address': 'House Address',
    'auth.dob': 'Date of Birth',
    'auth.conditions': 'Existing Conditions / Chronic Diseases',
    'auth.medications': 'Current Medications',
    'auth.ic_number': 'IC Number',
    'auth.full_name_ic': 'Name as per IC',
    'auth.phone_number': 'Phone Number',
    'auth.relationship': 'Relationship to Patient',
    'auth.family': 'Family',
    'auth.professional': 'Professional Caregiver',
    'auth.friend': 'Friend',
    'auth.agency_id': 'Agency ID (Optional)',
    'auth.license_number': 'License Number (Medical Board ID)',
    'auth.signature': 'Digital Signature (Type Full Name)',
    'auth.logout': 'Logout',
    'auth.google_login': 'Continue with Google',
    'nav.dashboard': 'Dashboard',
    'nav.insights': 'Insights',
    'nav.chat': 'Chat',
    'nav.calendar': 'Calendar',
    'nav.community': 'Community',
    'nav.health_circle': 'Health Circle',
    'nav.patient_profile': 'Patient Profile',
    'nav.health_circle_caregiver': 'Patient Profile',
    'nav.health_circle_patient': 'Care Network',
    'nav.settings': 'Settings',
    'nav.admin': 'Admin',
    'dashboard.greeting_morning': 'Good Morning',
    'dashboard.greeting_afternoon': 'Good Afternoon',
    'dashboard.greeting_evening': 'Good Evening',
    'dashboard.tagline': 'The Luminescent Guardian',
    'dashboard.health_priority': 'Your health is our priority. Here is your clinical overview for today.',
    'dashboard.caregiver_view': 'You are currently viewing {name}\'s health dashboard.',
    'dashboard.vitals_title': 'Vitality Metrics',
    'dashboard.add_log': 'Add Log',
    'dashboard.log_vitals': 'Log Vitals',
    'dashboard.history_title': 'Clinical History',
    'onboarding.welcome': 'Welcome to AIHMs',
    'onboarding.welcome_desc': 'Let us show you how to use this app to better monitor your health.',
    'onboarding.role_title': 'Choose Your Role',
    'onboarding.role_desc': 'Are you a patient wanting to monitor your health, or a caregiver helping others?',
    'onboarding.vitals_title': 'Log Health Data',
    'onboarding.vitals_desc': 'You can record your weight, heart rate, and daily steps here for AI monitoring.',
    'onboarding.analysis_title': 'View AI Analysis',
    'onboarding.analysis_desc': 'Our AI will analyze your data and provide easy-to-understand health summaries.',
    'onboarding.chat_title': 'AI Chat Support',
    'onboarding.chat_desc': 'Have questions about health? Just ask our AI assistant anytime.',
    'onboarding.patient': 'Patient',
    'onboarding.caregiver': 'Caregiver',
    'onboarding.next': 'Next',
    'onboarding.start': 'Start Now',
    'onboarding.tutorial': 'Interactive Tutorial',
    'chat.header_tagline': 'Agentic Assistant',
    'chat.header_title': 'Health Chat',
    'chat.header_desc': 'Please let me know if you feel unwell or want to record vitals.',
    'chat.placeholder': 'Ask me anything...',
    'chat.welcome': 'Welcome. I am your AIHMs assistant. Please tell me about your health.',
    'chat.mic_error': 'Sorry, I cannot access your microphone. Please ensure you have allowed microphone access in your web browser.',
    'chat.mic_denied': 'Microphone access denied. Please allow microphone access to use voice functions.',
    'chat.ai_triage_result': 'AI Triage Result',
    'chat.status': 'Status',
    'chat.zone': 'Zone',
    'chat.action_emergency': 'Emergency',
    'chat.action_scheduling': 'Scheduling',
    'chat.action_community': 'Community',
    'chat.action_none': 'None',
    'insights.header_tagline': 'Clinical Intelligence',
    'insights.header_title': 'Health Insights',
    'insights.header_desc': 'Geriatric trend analysis powered by Malaysian medical protocols.',
    'insights.health_score': 'Health Score',
    'insights.ai_assessment': 'AI Assessment',
    'insights.alert_title': 'Proactive Health Alert',
    'insights.summary_title': 'Clinical Summary',
    'insights.generating': 'Analysis is being generated...',
    'insights.trend_report': 'Trend Report',
    'insights.verified': 'Verified against Malaysian CPG.',
    'insights.ai_assistance': 'AI Health Assistant',
    'insights.view_all': 'View All',
    'insights.systolic': 'Systolic',
    'insights.bp_trend': 'Blood Pressure Trend',
    'insights.heart_rate': 'Heart Rate',
    'insights.activity': 'Daily Activity (Steps)',
    'insights.sleep': 'Sleep Patterns (Hours)',
    'insights.mood': 'Mood & Emotional Well-being',
    'insights.recommendations': 'Recommendations',
    'insights.status_stable': 'Stable',
    'insights.status_normal': 'Normal',
    'insights.status_improving': 'Improving',
    'insights.status_restorative': 'Restorative',
    'insights.status_positive': 'Positive',
    'insights.rec_desc': 'Clinical actions proposed based on patient log readings and AIHMs intelligence.',
    'insights.live_updates': 'Real-Time Data',
    'insights.calculated_score': 'Health Status',
    'calendar.header_tagline': 'Time Management',
    'calendar.header_title': 'Health Schedule',
    'calendar.header_desc': 'Manage your medical appointments and community activities with precision.',
    'calendar.ai_suggestion': 'AI Suggestion',
    'calendar.ai_suggestion_desc': "Based on the patient log readings, I've suggested a follow-up with Dr. Lim on {date}. Would you like to confirm?",
    'calendar.placeholder_title': 'e.g., Dr. Lim Follow-up',
    'calendar.placeholder_location': 'e.g., Hospital Kuala Lumpur',
    'calendar.upcoming': 'Upcoming Events',
    'calendar.confirm': 'Confirm',
    'calendar.reschedule': 'Reschedule',
    'calendar.add_title': 'New Appointment',
    'calendar.event_title': 'Event Title',
    'calendar.location': 'Location (Optional)',
    'calendar.date': 'Date',
    'calendar.time': 'Time',
    'calendar.category': 'Category',
    'calendar.reminders': 'Enable Reminders',
    'calendar.reminders_desc': 'Notify me 15 mins before',
    'calendar.cancel': 'Cancel',
    'calendar.schedule': 'Schedule',
    'calendar.confirm_success': 'AI Suggestion confirmed!',
    'calendar.no_events_on_day': 'No events today.',
    'calendar.clear_selection': 'Clear',
    'calendar.delete_title': 'Delete Appointment?',
    'calendar.delete_desc': 'Are you sure you want to delete the appointment "{title}"? This action cannot be undone.',
    'calendar.delete_confirm': 'Delete',
    'calendar.cat_checkup': 'Annual Checkup',
    'calendar.cat_followup': 'Follow-up',
    'calendar.cat_specialist': 'Specialist',
    'calendar.cat_other': 'Other',
    'calendar.view_month': 'Month',
    'calendar.view_week': 'Week',
    'calendar.view_day': 'Day',
    'calendar.hospitals_title': 'Nearest Hospitals',
    'calendar.hospitals_desc': 'Based on your location, here are the nearest health facilities.',
    'calendar.nearest': 'Nearest',
    'calendar.get_location': 'Get Location',
    'community.header_tagline': 'Social Hub',
    'community.header_title': 'Community Pulse',
    'community.header_desc': 'Connecting elderly Malaysians for a healthier, active, and dignified lifestyle.',
    'community.create_circle': 'Create Circle',
    'community.create_post': 'Create Post',
    'community.who_to_follow': 'Who to follow',
    'community.recommended_circles': 'Recommended Circles',
    'community.follow': 'Follow',
    'community.following': 'Following',
    'community.join': 'Join',
    'community.joined': 'Joined',
    'community.rsvp_count': '{count} attending',
    'community.share_success': 'Link shared!',
    'community.no_recommendations': 'No recommendations yet',
    'community.search_placeholder': 'Search posts, members, or types...',
    'community.all_feed': 'All Feed',
    'community.no_posts': 'No community posts yet. Be the first to share!',
    'community.share': 'Share',
    'community.copied': 'Copied',
    'community.join_event': 'Join Event',
    'community.event_calendar_title': 'Community Event: {title}',
    'community.event_calendar_notes': 'Event location: {location}. Content: {content}',
    'community.delete_post_confirm': 'Are you sure you want to delete this post?',
    'community.pulse_title': 'Community Pulse',
    'community.active_circles': 'Active Circles',
    'community.members': 'members',
    'community.joined_btn': 'Joined',
    'community.join_btn': 'Join',
    'community.no_posts_search': 'No posts found for "{query}"',
    'community.no_posts_default': 'No community posts yet. Be the first to share!',
    'community.no_circles': 'No active circles yet. Be the first to start one!',
    'community.circle_tasks': 'Circle Tasks',
    'community.spirit_title': 'Community Spirit',
    'community.spirit_energetic': 'Our community is feeling Energetic today!',
    'community.spirit_progress': '{name} is {progress}% towards its goal!',
    'community.spirit_quiet': 'Quiet',
    'community.spirit_vibrant': 'Vibrant',
    'community.spirit_starting': 'Starting',
    'community.spirit_goal_reached': 'Goal Reached',
    'community.member_status': 'Community Member',
    'community.edit_profile': 'Edit Profile',
    'community.my_posts': 'My Posts',
    'community.leaders_peers': 'Leaders & Peers',
    'community.leader': 'Community Leader',
    'community.contributor': 'Top Contributor',
    'community.active_member': 'Active Member',
    'community.view_profile': 'View Profile',
    'community.share_something': 'Share Something',
    'community.post_type': 'Post Type',
    'community.post_type_event': 'Event',
    'community.post_type_health_tip': 'Health Tip',
    'community.post_type_question': 'Question',
    'community.post_type_update': 'Update',
    'community.posting_to': 'Post To',
    'community.title': 'Title',
    'community.location': 'Location',
    'community.event_date': 'Event Date',
    'community.content': 'Content',
    'community.sending': 'Sending...',
    'community.send_post': 'Send Post',
    'community.create_circle_title': 'Create New Circle',
    'community.circle_name': 'Circle Name',
    'community.description': 'Description',
    'community.choose_icon': 'Choose Icon',
    'community.creating': 'Creating...',
    'community.create_btn': 'Create Circle',
    'community.following_btn': 'Following',
    'community.follow_btn': 'Follow',
    'community.message': 'Message',
    'community.posts_count': 'Posts',
    'community.followers_count': 'Followers',
    'community.following_count': 'Following',
    'community.recent_activity': 'Recent Activity',
    'community.no_posts_user': 'No posts yet.',
    'community.no_followers': 'No followers yet.',
    'community.no_following': 'No following yet.',
    'community.delete_post_tooltip': 'Delete Post',
    'community.trending': 'Trending',
    'community.quote': '"Community is where your health journey becomes a shared victory. Together, we thrive and age with dignity."',
    'community.member': 'Member',
    'community.circle_name_placeholder': 'e.g. Morning Yoga',
    'community.circle_desc_placeholder': 'What is this circle about?',
    'community.bio': 'Bio',
    'community.bio_placeholder': 'Tell the community about yourself...',
    'community.default_bio': 'Dedicated to living a healthy and active lifestyle. Passionate about community gardening, morning walks, and sharing nutritious recipes with friends.',
    'community.likes': 'Likes',
    'community.bookmark': 'Bookmark',
    'community.unbookmark': 'Remove Bookmark',
    'community.active_bookmarks': 'Active Bookmarks',
    'community.saved_items': 'Saved Items',
    'community.comment': 'Comment',
    'community.delete_post_title': 'Delete Post',
    'community.notify_caregiver': 'Notify Caregiver',
    'community.report': 'Report',
    'community.report_success': 'Post has been reported to moderators.',
    'community.comments_title': 'Discussion',
    'community.responses': 'Responses',
    'community.no_comments': 'Be the first to join the conversation!',
    'community.write_comment': 'Add a comment...',
    'health_circle.header_tagline': 'Care Network',
    'health_circle.header_title': 'Health Circle',
    'health_circle.header_desc': 'Connect with your trusted caregivers to stay informed about your well-being.',
    'health_circle.privacy_title': 'Privacy & Consent',
    'health_circle.call': 'Voice Call',
    'health_circle.video_call': 'Video Call',
    'health_circle.chat': 'Direct Chat',
    'health_circle.coming_soon': 'This feature will be available soon.',
    'health_circle.my_caregivers': 'My Caregivers',
    'health_circle.linked_patients': 'Patients Under Care',
    'health_circle.privacy_desc': 'Your health data is only shared with caregivers who are officially linked via your Profile ID.',
    'health_circle.no_contacts': 'No contacts added yet.',
    'health_circle.add_desc': 'Add up to 3 family members or caregivers.',
    'health_circle.emergency_alerts': 'Emergency Alerts',
    'health_circle.weekly_summary': 'Weekly Summary',
    'health_circle.trusted_contact': 'Trusted Contact',
    'health_circle.add_contact': 'Add Contact',
    'health_circle.full_name': 'Full Name',
    'health_circle.relation': 'Relationship',
    'health_circle.email': 'Email',
    'health_circle.phone': 'Phone Number',
    'health_circle.saving': 'Saving...',
    'health_circle.limit_alert': 'You can only add up to 3 trusted contacts.',
    'health_circle.delete_confirm': 'Are you sure you want to delete this contact?',
    'drawer.emergency_title': 'Emergency Actions',
    'drawer.sos_button': 'Trigger SOS',
    'drawer.sos_desc': 'Alert all trusted contacts',
    'drawer.sos_confirm_title': 'Confirm SOS',
    'drawer.sos_confirm_desc': 'This will immediately alert your caregivers and emergency contacts with your current location.',
    'drawer.sos_confirm_btn': 'Yes, Trigger SOS',
    'drawer.sos_success': 'SOS Activated',
    'drawer.sos_success_desc': 'Your trusted contacts have been alerted. Help is on the way.',
    'drawer.sending': 'Sending Alerts...',
    'drawer.sending_desc': 'Locating device and contacting emergency network. Please stay calm.',
    'drawer.navigation_title': 'Main Menu',
    'drawer.support_title': 'Support & Info',
    'drawer.help_center': 'Help Center',
    'drawer.about': 'About AIHMs',
    'settings.header_tagline': 'Control Center',
    'settings.header_desc': 'Configure your AIHMs experience, privacy, and connected devices.',
    'settings.location_sharing_active': 'Location Sharing Active',
    'settings.role_caregiver': 'Caregiver',
    'settings.role_patient': 'Patient',
    'settings.role_leader': 'Leader',
    'settings.role_contributor': 'Contributor',
    'settings.role_member': 'Member',
    'settings.active_account': 'Active Account',
    'settings.theme_desc': 'Customize the app colors to your comfort.',
    'settings.language_desc': 'Choose your preferred language for the app.',
    'theme.emerald': 'Emerald Forest',
    'theme.sapphire': 'Royal Sapphire',
    'theme.harvest': 'Golden Harvest',
    'theme.lavender': 'Serene Lavender',
    'settings.link_patient_title': 'Link Patient',
    'settings.link_patient_desc': 'Enter Patient ID to monitor their health.',
    'settings.patient_id_label': 'Patient ID',
    'settings.patient_id_placeholder': 'Enter Patient ID',
    'settings.patient_id_hint': 'This ID can be found in the patient\'s profile.',
    'settings.linking': 'Linking...',
    'settings.link': 'Link',
    'settings.update_profile_title': 'Update Profile',
    'settings.update_profile_desc': 'Update your personal information here.',
    'settings.display_name_label': 'Display Name',
    'settings.display_name_placeholder': 'Enter your name',
    'settings.photo_url_label': 'Profile Photo URL',
    'settings.regenerate': 'Regenerate',
    'settings.saving': 'Saving...',
    'settings.save': 'Save',
    'settings.change_role_title': 'Change Role',
    'settings.change_role_desc': 'Select your role in AIHMs.',
    'settings.role_patient_desc': 'Monitor your health and receive reminders.',
    'settings.role_caregiver_desc': 'Monitor the health of your family members or patients.',
    'settings.privacy_controls_title': 'Privacy Controls',
    'settings.privacy_controls_desc': 'Manage your data and sharing permissions.',
    'settings.location_sharing_label': 'Location Sharing',
    'settings.location_sharing_hint': 'Allow AIHMs to share your location with caregivers during emergencies.',
    'settings.data_sharing_label': 'Caregiver Data Sharing',
    'settings.data_sharing_hint': 'Linked caregivers can view your health logs and vital data.',
    'settings.third_party_label': 'Third-Party Services',
    'settings.third_party_hint': 'Manage connections to devices like Fitbit and Google Fit.',
    'dashboard.wearable_connected': 'Wearable Connected',
    'dashboard.last_synced': 'Last synced',
    'dashboard.never': 'Never',
    'dashboard.clarity_title': 'Daily Clarity',
    'dashboard.clarity_desc': 'Don\'t forget your morning medication with breakfast. Your heart rate is stable.',
    'dashboard.medication_logged': 'Medication Logged',
    'dashboard.triage_red_label': 'Emergency',
    'dashboard.triage_red_desc': 'Immediate medical attention required.',
    'dashboard.triage_yellow_label': 'Urgent',
    'dashboard.triage_yellow_desc': 'Please monitor closely and consult a nurse.',
    'dashboard.triage_green_label': 'Stable',
    'dashboard.triage_green_desc': 'Vitals are within acceptable range.',
    'dashboard.triage_none_label': 'No Data',
    'dashboard.triage_none_desc': 'Log your vitals to see status.',
    'dashboard.goals_title': 'Goal Rings',
    'dashboard.daily_steps': 'Daily Steps',
    'dashboard.log_vitals_desc': 'Update your health record manually',
    'dashboard.monitor_closely': 'Monitor Closely',
    'dashboard.save_record': 'Save Health Record',
    'dashboard.save_success': 'Health record saved successfully.',
    'dashboard.full_archive': 'Full Archive',
    'dashboard.no_records': 'No records found. Start your journey today.',
    'history.archive_desc': 'Complete historical records of health logs for {target}.',
    'history.total_records': 'Total Records',
    'history.search_logs': 'Search notes, status...',
    'history.all_zones': 'All Statuses',
    'history.delete_title': 'Delete Record?',
    'history.delete_desc': 'This will permanently remove this health entry from the history log. This action cannot be undone.',
    'history.no_records_found': 'No Records Found',
    'history.adjust_filters': 'Try adjusting your filters or searches to find specific logs.',
    'dashboard.zone_red': 'Red Zone',
    'dashboard.zone_yellow': 'Yellow Zone',
    'dashboard.zone_green': 'Green Zone',
    'metrics.activity': 'Activity',
    'metrics.steps': 'steps',
    'metrics.heart_rate': 'Heart Rate',
    'metrics.weight': 'Weight',
    'metrics.blood_pressure': 'Blood Pressure',
    'metrics.sleep': 'Sleep',
    'metrics.hours': 'Hours',
    'metrics.mood': 'Mood',
    'metrics.heart': 'Heart',
    'metrics.bp': 'BP',
    'metrics.kg': 'kg',
    'metrics.bpm': 'bpm',
    'metrics.h': 'h',
    'mood.title': 'Mood',
    'mood.poor': 'Poor',
    'mood.fair': 'Fair',
    'mood.neutral': 'Neutral',
    'mood.good': 'Good',
    'mood.excellent': 'Excellent',
    'settings.title': 'App Settings',
    'settings.language': 'Language',
    'settings.theme': 'App Theme',
    'settings.logout': 'Logout',
    'settings.profile': 'Profile',
    'settings.role': 'Role',
    'settings.privacy': 'Privacy Controls',
    'settings.care_network': 'Care Network',
    'settings.health_services': 'Health Services',
    'settings.preferences': 'Preferences',
    'settings.select_language': 'Select Language',
    'settings.select_theme': 'Select Theme',
    'dashboard.greeting_user_default': 'Sir/Madam',
    'feedback.title': 'Feedback',
    'feedback.desc': 'How is your experience using AIHMs? Please share any suggestions or issues you encountered.',
    'feedback.label': 'Your Message',
    'feedback.placeholder': 'Write your feedback here...',
    'feedback.submit': 'Submit Feedback',
    'feedback.submitting': 'Sending...',
    'feedback.thanks': 'Thank You!',
    'feedback.thanks_desc': 'Your feedback has been submitted. We appreciate your support.',
    'health_circle.add_up_to': 'Add up to 3 family members or caregivers.',
    'health_circle.relationship': 'Relationship',
    'health_circle.placeholder_email': 'ahmad@email.com',
    'health_circle.placeholder_phone': '+60123456789',
    'health_circle.add_placeholder_name': 'Example: John Doe',
    'health_circle.add_placeholder_relation': 'Example: Son / Caregiver',
    'health_circle.enable_alerts': 'Enable Alerts',
    'health_circle.enable_reports': 'Enable Reports',
    'health_circle.cancel': 'Cancel',
    'health_circle.add': 'Add',
    'notification.reminder_title': 'Appointment Reminder: {title}',
    'notification.reminder_body': 'Your appointment starts at {time}.',
    'common.close': 'Close',
    'common.view_details': 'View Details',
    'common.cancel': 'Cancel',
    'common.anonymous': 'Anonymous',
    'common.delete': 'Delete',
    'common.back_to_dashboard': 'Back to Dashboard',
    'common.you': 'you',
    'calendar.add_event': 'Add Event',
    'calendar.events': 'Events',
    'calendar.no_records': 'No records',
    'calendar.no_upcoming': 'No upcoming events',
    'calendar.records': 'Records',
    'calendar.records_count': 'records',
    'calendar.return_to_today': 'Return to today',
    'chat.start_chat': 'Start Chat',
    'dashboard.current_status': 'Current Status',
    'dashboard.delete_confirm': 'Are you sure you want to delete this?',
    'dashboard.delete_confirm_title': 'Confirm Delete',
    'dashboard.log_notes': 'Log Notes',
    'dashboard.metric_desc_prefix': '',
    'dashboard.metric_desc_suffix': '',
    'dashboard.record_details': 'Record Details',
    'dashboard.within_healthy_range': 'Within healthy range',
    'health_circle.delete_confirm_title': 'Confirm Delete',
    'settings.add_reminder': 'Add Reminder',
    'chat.ai_extracted_notes': 'AI extracted from chat: {text}',
    'community.post_type_tip': 'Tip',
    'community.post_type_milestone': 'Milestone',
    'settings.section_account': 'Account',
    'settings.label_profile': 'Profile',
    'settings.label_role': 'Role',
    'settings.label_privacy': 'Privacy',
    'settings.section_care_network': 'Care Network',
    'settings.label_link_patient': 'Link Patient',
    'settings.status_linked': 'Linked',
    'settings.status_not_linked': 'Not Linked',
    'settings.main_caregiver_title': 'Primary Caregiver',
    'settings.main_caregiver_desc': 'Select the main person to be contacted in case of emergency.',
    'settings.label_my_caregivers': 'My Caregivers',
    'settings.status_none': 'None',
    'settings.section_health_services': 'Health Services',
    'settings.label_emergency_location': 'Emergency Location',
    'settings.status_active': 'Active',
    'settings.status_disabled': 'Disabled',
    'settings.label_wearable': 'Wearable Integration',
    'settings.status_syncing': 'Syncing...',
    'settings.status_fitbit_connected': 'Fitbit Connected',
    'settings.status_not_connected': 'Not Connected',
    'settings.section_preferences': 'Preferences',
    'settings.label_smart_notifications': 'Smart Notifications',
    'settings.notifications_enabled_title': 'Notifications Enabled',
    'settings.notifications_enabled_body': 'You will now receive health reminders and alerts.',
    'settings.confirm_role_caregiver': 'Are you sure you want to change your role to Caregiver? You will be able to monitor linked patients.',
    'settings.confirm_role_patient': 'Are you sure you want to change your role to Patient? You will be able to monitor your own health.',
    'settings.patient_id_not_found': 'Patient ID not found.',
    'settings.not_a_patient': 'The ID provided does not belong to a patient.',
    'settings.fitbit_connect_error': 'Failed to connect to Fitbit. Please try again.',
    'settings.fitbit_sync_success': 'Fitbit data synced successfully!',
    'settings.fitbit_sync_error': 'Failed to sync Fitbit data.',
    'settings.synced_from_fitbit': 'Synced from Fitbit',
    'settings.clinical_id_title': 'Clinical Identity Card',
    'settings.clinical_id_desc': 'This virtual ID card makes it easy to share clinical information with your caregiver.',
    'settings.view_id_card': 'View ID Card',
    'settings.copy_id': 'Copy ID',
    'settings.id_copied': 'ID copied to clipboard!',
    'settings.invite_token': 'Invite Token',
    'settings.refresh_token': 'Refresh',
    'settings.expires_in': 'Expires in',
    'settings.no_active_token': 'No active token',
    'settings.generate_now': 'Generate Now',
    'settings.linkage_tip': 'Share this code and your Patient ID with your caregiver to link accounts.',
    'settings.invite_token_label': 'Invite Token',
    'settings.link_account': 'Link Account',
    'settings.linkage_help': 'Ask the patient to open their profile ID card to see their ID and temporary invite token.',
    'settings.invalid_token': 'Invalid invite token',
    'settings.token_expired': 'Invite token has expired',
    'settings.blood_type': 'Blood Type',
    'settings.allergies': 'Allergies',
    'settings.emergency_contact': 'Emergency',
    'settings.full_id': 'Full ID',
    'wearables.header_tagline': 'Device Integration',
    'wearables.header_title': 'Smart Watch Hub',
    'wearables.header_desc': 'Connect your favourite wearables to AIHMs for seamless, real-time health monitoring.',
    'wearables.header_desc_caregiver': 'Managing {name}\'s wearable devices. Sync vitals and health data with AIHMs to monitor their wellbeing.',
    'wearables.connect_fitbit': 'Connect Fitbit',
    'wearables.connect_apple': 'Connect Apple Health',
    'wearables.connect_google': 'Connect Google Fit',
    'wearables.sync_now': 'Sync Now',
    'wearables.simulate_sync': 'Simulate Sync (Demo)',
    'wearables.coming_soon': 'Coming Soon for Web',
    'wearables.steps_desc': 'Track your daily activity and targets.',
    'wearables.heart_desc': 'Real-time resting heart rate monitoring.',
    'wearables.sleep_desc': 'Analyze your recovery and sleep cycles.',
    'community.task_morning_walk': 'Daily Morning Walk',
    'community.task_recipe_share': 'Healthy Recipe Share',
    'community.task_group_chat': 'Weekly Group Chat',
    'language.ms': 'Bahasa Melayu',
    'language.en': 'English',
    'language.zh': 'Mandarin (中文)',
  },
  zh: {
    'app.name': 'AIHMs 守护者',
    'app.tagline': '基于人工智能的老年健康监测系统。',
    'app.loading': '正在加载 AIHMs',
    'auth.login': '登录',
    'auth.register': '注册账号',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.username': '用户名',
    'auth.role': '角色',
    'auth.no_account': '没有账号？立即注册',
    'auth.have_account': '已有账号？登录',
    'auth.login_btn': '登录',
    'auth.register_btn': '注册',
    'auth.invalid_email': '无效的邮箱',
    'auth.email_in_use': '此电子邮件已被另一个帐户使用。',
    'auth.invalid_credentials': '邮箱或密码无效。请再试一次。',
    'auth.weak_password': '密码太弱（至少 6 个字符）',
    'auth.required': '必填项',
    'auth.access_code': '访问码',
    'auth.invalid_code': '访问码无效',
    'auth.gender': '性别',
    'auth.male': '男',
    'auth.female': '女',
    'auth.other': '其他',
    'auth.blood_type': '血型',
    'auth.address': '家庭住址',
    'auth.dob': '出生日期',
    'auth.conditions': '现有状况/慢性病',
    'auth.medications': '当前药物',
    'auth.ic_number': '身份证号码 (IC)',
    'auth.full_name_ic': '身份证姓名',
    'auth.phone_number': '电话号码',
    'auth.relationship': '与患者的关系',
    'auth.family': '家人',
    'auth.professional': '专业护理人员',
    'auth.friend': '朋友',
    'auth.agency_id': '机构 ID (如有)',
    'auth.license_number': '执照号码 (医委 ID)',
    'auth.signature': '数字签名 (输入全名)',
    'auth.logout': '退出登录',
    'auth.google_login': '使用 Google 登录',
    'nav.dashboard': '仪表板',
    'nav.insights': '洞察',
    'nav.chat': '聊天',
    'nav.calendar': '日历',
    'nav.community': '社区',
    'nav.health_circle': '健康圈子',
    'nav.patient_profile': '患者资料',
    'nav.health_circle_caregiver': '患者资料',
    'nav.health_circle_patient': '护理网络',
    'nav.settings': '设置',
    'dashboard.greeting_morning': '早上好',
    'dashboard.greeting_afternoon': '下午好',
    'dashboard.greeting_evening': '晚上好',
    'dashboard.tagline': '发光守护者',
    'dashboard.health_priority': '您的健康是我们的首要任务。这是您今天的临床概览。',
    'dashboard.caregiver_view': '您目前正在查看 {name} 的健康仪表板。',
    'dashboard.vitals_title': '生命体征指标',
    'dashboard.add_log': '添加日志',
    'dashboard.log_vitals': '记录生命体征',
    'dashboard.history_title': '临床历史',
    'onboarding.welcome': '欢迎来到 AIHMs',
    'onboarding.welcome_desc': '让我们向您展示如何使用此应用程序来更好地监测您的健康。',
    'onboarding.role_title': '选择您的角色',
    'onboarding.role_desc': '您是想要监测健康的患者，还是帮助他人的护理人员？',
    'onboarding.vitals_title': '记录健康数据',
    'onboarding.vitals_desc': '您可以在此处记录您的体重、心率和每日步数，以便 AI 进行监测。',
    'onboarding.analysis_title': '查看 AI 分析',
    'onboarding.analysis_desc': '我们的 AI 将分析您的数据并提供易于理解的健康摘要。',
    'onboarding.chat_title': 'AI 聊天支持',
    'onboarding.chat_desc': '有关于健康的问题吗？随时询问我们的 AI 助手。',
    'onboarding.patient': '患者',
    'onboarding.caregiver': '护理人员',
    'onboarding.next': '下一步',
    'onboarding.start': '现在开始',
    'onboarding.tutorial': '互动教程',
    'chat.header_tagline': '代理助手',
    'chat.header_title': '健康聊天',
    'chat.header_desc': '如果您感到不适或想要记录生命体征，请告诉我。',
    'chat.placeholder': '问我任何问题...',
    'chat.welcome': '欢迎。我是您的 AIHMs 助手。请告诉我您的健康状况。',
    'chat.mic_error': '抱歉，我无法访问您的麦克风。请确保您已在网络浏览器中允许麦克风访问。',
    'chat.mic_denied': '麦克风访问被拒绝。请允许麦克风访问以使用语音功能。',
    'chat.ai_triage_result': 'AI 分诊结果',
    'chat.status': '状态',
    'chat.zone': '区',
    'chat.action_emergency': '紧急',
    'chat.action_scheduling': '安排',
    'chat.action_community': '社区',
    'chat.action_none': '无',
    'insights.header_tagline': '临床智能',
    'insights.header_title': '健康洞察',
    'insights.header_desc': '基于马来西亚医疗协议的老年趋势分析。',
    'insights.health_score': '健康评分',
    'insights.ai_assessment': 'AI 评估',
    'insights.alert_title': '主动健康警报',
    'insights.summary_title': '临床摘要',
    'insights.generating': '分析正在生成中...',
    'insights.trend_report': '趋势报告',
    'insights.verified': '已根据马来西亚 CPG 进行验证。',
    'insights.systolic': '收缩压',
    'insights.bp_trend': '血压趋势',
    'insights.heart_rate': '心率',
    'insights.activity': '每日活动 (步数)',
    'insights.sleep': '睡眠模式 (小时)',
    'insights.mood': '情绪与心理健康',
    'insights.recommendations': '建议',
    'insights.status_stable': '稳定',
    'insights.status_normal': '正常',
    'insights.status_improving': '正在改善',
    'insights.status_restorative': '恢复性',
    'insights.status_positive': '积极',
    'insights.rec_desc': '根据患者日志读数和 AIHMs 智能分析建议的临床行动。',
    'insights.live_updates': '实时数据',
    'insights.calculated_score': '健康状况',
    'calendar.header_tagline': '时间管理',
    'calendar.header_title': '健康日程',
    'calendar.header_desc': '精确管理您的医疗预约和社区活动。',
    'calendar.ai_suggestion': 'AI 建议',
    'calendar.ai_suggestion_desc': '根据最近的患者日志记录，我建议在 {date} 与林医生进行随访。您想确认吗？',
    'calendar.placeholder_title': '例如：林医生随访',
    'calendar.placeholder_location': '例如：吉隆坡医院',
    'calendar.upcoming': '即将到来的活动',
    'calendar.confirm': '确认',
    'calendar.reschedule': '重新安排',
    'calendar.add_title': '新预约',
    'calendar.event_title': '活动标题',
    'calendar.location': '地点 (可选)',
    'calendar.date': '日期',
    'calendar.time': '时间',
    'calendar.category': '类别',
    'calendar.reminders': '启用提醒',
    'calendar.reminders_desc': '提前 15 分钟通知我',
    'calendar.cancel': '取消',
    'calendar.schedule': '安排',
    'calendar.confirm_success': 'AI建议已确认！',
    'calendar.no_events_on_day': '今天没有活动。',
    'calendar.clear_selection': '清除',
    'calendar.delete_title': '删除预约？',
    'calendar.delete_desc': '您确定要删除预约 "{title}" 吗？此操作无法撤销。',
    'calendar.delete_confirm': '删除',
    'calendar.cat_checkup': '年度检查',
    'calendar.cat_followup': '随访',
    'calendar.cat_specialist': '专科',
    'calendar.cat_other': '其他',
    'calendar.view_month': '月',
    'calendar.view_week': '周',
    'calendar.view_day': '日',
    'calendar.hospitals_title': '附近的医院',
    'calendar.hospitals_desc': '根据您的位置，这些是最近的医疗设施。',
    'calendar.nearest': '最近',
    'calendar.get_location': '获取位置',
    'community.header_tagline': '社交中心',
    'community.header_title': '社区脉搏',
    'community.header_desc': '连接马来西亚老年人，打造更健康、更活跃、更有尊严的生活方式。',
    'community.create_circle': '创建圈子',
    'community.create_post': '创建帖子',
    'community.who_to_follow': '推荐关注',
    'community.recommended_circles': '推荐圈子',
    'community.follow': '关注',
    'community.following': '已关注',
    'community.join': '加入',
    'community.joined': '已加入',
    'community.rsvp_count': '{count} 人将参加',
    'community.share_success': '链接已分享！',
    'community.no_recommendations': '暂无推荐',
    'community.search_placeholder': '搜索帖子、成员或类型...',
    'community.all_feed': '所有动态',
    'community.no_posts': '目前还没有社区帖子。成为第一个分享的人吧！',
    'community.share': '分享',
    'community.copied': '已复制',
    'community.join_event': '参加活动',
    'community.event_calendar_title': '社区活动：{title}',
    'community.event_calendar_notes': '活动地点：{location}。内容：{content}',
    'community.delete_post_confirm': '您确定要删除此帖子吗？',
    'community.pulse_title': '社区脉搏',
    'community.active_circles': '活跃圈子',
    'community.members': '成员',
    'community.joined_btn': '已加入',
    'community.join_btn': '加入',
    'community.no_posts_search': '未找到关于 "{query}" 的帖子',
    'community.no_posts_default': '目前还没有社区帖子。成为第一个分享的人吧！',
    'community.no_circles': '尚未有活跃圈子。成为第一个创建的人吧！',
    'community.circle_tasks': '圈子任务',
    'community.spirit_title': '社区精神',
    'community.spirit_energetic': '我们的社区今天充满活力！',
    'community.spirit_progress': '{name} 已完成目标的 {progress}%！',
    'community.spirit_quiet': '安静',
    'community.spirit_vibrant': '活跃',
    'community.spirit_starting': '开始',
    'community.spirit_goal_reached': '达到目标',
    'community.member_status': '社区成员',
    'community.edit_profile': '编辑个人资料',
    'community.my_posts': '我的帖子',
    'community.leaders_peers': '领导者与同行',
    'community.leader': '社区领导者',
    'community.contributor': '顶级贡献者',
    'community.active_member': '活跃成员',
    'community.view_profile': '查看个人资料',
    'community.share_something': '分享一些东西',
    'community.post_type': '帖子类型',
    'community.post_type_event': '活动',
    'community.post_type_health_tip': '健康贴士',
    'community.post_type_question': '问题',
    'community.post_type_update': '更新',
    'community.posting_to': '发布到',
    'community.title': '标题',
    'community.location': '地点',
    'community.event_date': '活动日期',
    'community.content': '内容',
    'community.sending': '发送中...',
    'community.send_post': '发送帖子',
    'community.create_circle_title': '创建新圈子',
    'community.circle_name': '圈子名称',
    'community.description': '描述',
    'community.choose_icon': '选择图标',
    'community.creating': '创建中...',
    'community.create_btn': '创建圈子',
    'community.following_btn': '关注中',
    'community.follow_btn': '关注',
    'community.message': '消息',
    'community.posts_count': '帖子',
    'community.followers_count': '粉丝',
    'community.following_count': '关注中',
    'community.recent_activity': '近期活动',
    'community.no_posts_user': '目前还没有帖子。',
    'community.no_followers': '目前还没有粉丝。',
    'community.no_following': '目前还没有关注的人。',
    'community.delete_post_tooltip': '删除帖子',
    'community.trending': '热门',
    'community.quote': '“社区是您的健康之旅成为共同胜利的地方。齐心协力，我们共同成长，尊严地老去。”',
    'community.member': '成员',
    'community.circle_name_placeholder': '例如：早晨瑜伽',
    'community.circle_desc_placeholder': '这个圈子是关于什么的？',
    'community.bio': '个人简介',
    'community.bio_placeholder': '向社区介绍你自己...',
    'community.default_bio': '致力于过上健康活跃的生活。热爱社区园艺、晨练，并与朋友分享营养食谱。',
    'community.likes': '点赞',
    'community.bookmark': '收藏',
    'community.unbookmark': '取消收藏',
    'community.active_bookmarks': '活跃收藏',
    'community.saved_items': '已收藏项目',
    'community.comment': '评论',
    'community.delete_post_title': '删除帖子',
    'community.notify_caregiver': '通知照护者',
    'community.report': '举报',
    'community.report_success': '帖子已举报给管理员。',
    'community.comments_title': '讨论',
    'community.responses': '回复',
    'community.no_comments': '率先参与讨论吧！',
    'community.write_comment': '添加评论...',
    'health_circle.header_tagline': '护理网络',
    'health_circle.header_title': '健康圈子',
    'health_circle.header_desc': '与您信任的护理人员联系，随时了解您的健康状况。',
    'health_circle.privacy_title': '隐私与同意',
    'health_circle.call': '语音通话',
    'health_circle.video_call': '视频通话',
    'health_circle.chat': '直接聊天',
    'health_circle.coming_soon': '此功能即将推出。',
    'health_circle.my_caregivers': '我的护理人员',
    'health_circle.linked_patients': '所照顾的患者',
    'health_circle.privacy_desc': '您的健康数据仅与通过您的资料 ID 正式关联的护理人员共享。',
    'health_circle.no_contacts': '尚未添加联系人。',
    'health_circle.add_desc': '最多添加 3 名家庭成员或护理人员。',
    'health_circle.emergency_alerts': '紧急警报',
    'health_circle.weekly_summary': '每周摘要',
    'health_circle.trusted_contact': '信任联系人',
    'health_circle.add_contact': '添加联系人',
    'health_circle.full_name': '全名',
    'health_circle.relation': '关系',
    'health_circle.email': '电子邮件',
    'health_circle.phone': '电话号码',
    'health_circle.saving': '保存中...',
    'health_circle.limit_alert': '您最多只能添加 3 个信任联系人。',
    'health_circle.delete_confirm': '您确定要删除此联系人吗？',
    'drawer.emergency_title': '紧急行动',
    'drawer.sos_button': '触发 SOS',
    'drawer.sos_desc': '通知所有信任联系人',
    'drawer.sos_confirm_title': '确认 SOS',
    'drawer.sos_confirm_desc': '这会立即使用您当前的位置通知您的看护人和紧急联系人。',
    'drawer.sos_confirm_btn': '是，触发 SOS',
    'drawer.sos_success': 'SOS 已激活',
    'drawer.sos_success_desc': '您的信任联系人已收到警报。救援马上就到。',
    'drawer.sending': '正在发送警报...',
    'drawer.sending_desc': '正在定位设备并联系紧急网络。请保持冷静。',
    'drawer.navigation_title': '主菜单',
    'drawer.support_title': '支持与信息',
    'drawer.help_center': '帮助中心',
    'drawer.about': '关于 AIHMs',
    'settings.header_tagline': '控制中心',
    'settings.header_desc': '配置您的 AIHMs 体验、隐私和连接的设备。',
    'settings.location_sharing_active': '位置共享已激活',
    'settings.role_caregiver': '护理人员',
    'settings.role_patient': '患者',
    'settings.role_leader': '领导者',
    'settings.role_contributor': '贡献者',
    'settings.role_member': '成员',
    'settings.active_account': '活跃账户',
    'settings.theme_desc': '根据您的舒适度自定义应用颜色。',
    'settings.language_desc': '为应用选择您偏好的语言。',
    'theme.emerald': '翡翠森林',
    'theme.sapphire': '皇家蓝宝石',
    'theme.harvest': '金色收获',
    'theme.lavender': '宁静薰衣草',
    'settings.link_patient_title': '关联患者',
    'settings.link_patient_desc': '输入患者 ID 以监测其健康状况。',
    'settings.patient_id_label': '患者 ID',
    'settings.patient_id_placeholder': '输入患者 ID',
    'settings.patient_id_hint': '此 ID 可以在患者的个人资料中找到。',
    'settings.linking': '关联中...',
    'settings.link': '关联',
    'settings.update_profile_title': '更新个人资料',
    'settings.update_profile_desc': '在此更新您的个人信息。',
    'settings.display_name_label': '显示名称',
    'settings.display_name_placeholder': '输入您的姓名',
    'settings.photo_url_label': '个人资料照片 URL',
    'settings.regenerate': '重新生成',
    'settings.saving': '保存中...',
    'settings.save': '保存',
    'settings.change_role_title': '更改角色',
    'settings.change_role_desc': '在 AIHMs 中选择您的角色。',
    'settings.role_patient_desc': '监测您的健康并接收提醒。',
    'settings.role_caregiver_desc': '监测您的家庭成员或患者的健康。',
    'settings.privacy_controls_title': '隐私控制',
    'settings.privacy_controls_desc': '管理您的数据和共享权限。',
    'settings.location_sharing_label': '位置共享',
    'settings.location_sharing_hint': '允许 AIHMs 在紧急情况下与护理人员共享您的位置。',
    'settings.data_sharing_label': '护理人员数据共享',
    'settings.data_sharing_hint': '关联的护理人员可以查看您的健康日志和关键数据。',
    'settings.third_party_label': '第三方服务',
    'settings.third_party_hint': '管理与 Fitbit 和 Google Fit 等设备的连接。',
    'dashboard.wearable_connected': '可穿戴设备已连接',
    'dashboard.last_synced': '上次同步',
    'dashboard.never': '从不',
    'dashboard.clarity_title': '每日清晰度',
    'dashboard.clarity_desc': '别忘了吃早餐时服用早晨的药物。您的心率稳定。',
    'dashboard.medication_logged': '药物已记录',
    'dashboard.triage_red_label': '紧急 (Emergency)',
    'dashboard.triage_red_desc': '需要立即就医。',
    'dashboard.triage_yellow_label': '紧迫 (Urgent)',
    'dashboard.triage_yellow_desc': '请密切监测并咨询护士。',
    'dashboard.triage_green_label': '稳定',
    'dashboard.triage_green_desc': '生命体征在可接受范围内。',
    'dashboard.triage_none_label': '无数据',
    'dashboard.triage_none_desc': '记录您的生命体征以查看状态。',
    'dashboard.goals_title': '目标环',
    'dashboard.daily_steps': '每日步数',
    'dashboard.log_vitals_desc': '手动更新您的健康记录',
    'dashboard.monitor_closely': '密切关注',
    'dashboard.save_record': '保存健康记录',
    'dashboard.save_success': '健康记录保存成功。',
    'dashboard.full_archive': '完整存档',
    'dashboard.no_records': '未找到记录。今天就开始您的旅程吧。',
    'history.archive_desc': '{target} 的完整健康日志历史记录。',
    'history.total_records': '记录总数',
    'history.search_logs': '搜索备注、状态...',
    'history.all_zones': '所有状态',
    'history.delete_title': '删除记录？',
    'history.delete_desc': '这将从历史日志中永久删除此健康条目。此操作无法撤销。',
    'history.no_records_found': '未找到记录',
    'history.adjust_filters': '尝试调整您的过滤器或搜索以查找特定日志。',
    'dashboard.zone_red': '红色区域',
    'dashboard.zone_yellow': '黄色区域',
    'dashboard.zone_green': '绿色区域',
    'metrics.activity': '活动',
    'metrics.steps': '步',
    'metrics.heart_rate': '心率',
    'metrics.weight': '体重',
    'metrics.blood_pressure': '血压',
    'metrics.sleep': '睡眠',
    'metrics.hours': '小时',
    'metrics.mood': '情绪',
    'metrics.heart': '心脏',
    'metrics.bp': '血压',
    'metrics.kg': '公斤',
    'metrics.bpm': '次/分',
    'metrics.h': '小时',
    'mood.title': '情绪',
    'mood.poor': '差',
    'mood.fair': '一般',
    'mood.neutral': '中立',
    'mood.good': '好',
    'mood.excellent': '极好',
    'settings.title': '应用设置',
    'settings.language': '语言',
    'settings.theme': '应用主题',
    'settings.logout': '退出 AIHMs',
    'settings.profile': '个人资料',
    'settings.role': '角色',
    'settings.privacy': '隐私控制',
    'settings.care_network': '护理网络',
    'settings.health_services': '健康服务',
    'settings.preferences': '偏好',
    'settings.select_language': '选择语言',
    'settings.select_theme': '选择主题',
    'dashboard.greeting_user_default': '先生/女士',
    'feedback.title': '反馈',
    'feedback.desc': '您使用 AIHMs 的体验如何？请分享您遇到的任何建议或问题。',
    'feedback.label': '您的信息',
    'feedback.placeholder': '在这里写下您的反馈...',
    'feedback.submit': '提交反馈',
    'feedback.submitting': '发送中...',
    'feedback.thanks': '谢谢！',
    'feedback.thanks_desc': '您的反馈已提交。我们感谢您的支持。',
    'health_circle.add_up_to': '最多添加 3 名家庭成员或护理人员。',
    'health_circle.relationship': '关系',
    'health_circle.placeholder_email': 'ahmad@email.com',
    'health_circle.placeholder_phone': '+60123456789',
    'health_circle.add_placeholder_name': '例如：张三',
    'health_circle.add_placeholder_relation': '例如：儿子 / 护理人员',
    'health_circle.enable_alerts': '启用警报',
    'health_circle.enable_reports': '启用报告',
    'health_circle.cancel': '取消',
    'health_circle.add': '添加',
    'notification.reminder_title': '预约提醒：{title}',
    'notification.reminder_body': '您的预约在 {time} 开始。',
    'common.close': '关闭',
    'common.view_details': '查看详情',
    'common.cancel': '取消',
    'common.anonymous': '匿名',
    'common.delete': '删除',
    'common.back_to_dashboard': '回到主页',
    'common.you': '您',
    'calendar.add_event': '添加活动',
    'calendar.events': '活动',
    'calendar.no_records': '没有记录',
    'calendar.no_upcoming': '没有即将到来的活动',
    'calendar.records': '记录',
    'calendar.records_count': '条记录',
    'calendar.return_to_today': '返回今天',
    'chat.start_chat': '开始聊天',
    'dashboard.current_status': '当前状态',
    'dashboard.delete_confirm': '您确定要删除吗？',
    'dashboard.delete_confirm_title': '确认删除',
    'dashboard.log_notes': '日志说明',
    'dashboard.metric_desc_prefix': '',
    'dashboard.metric_desc_suffix': '',
    'dashboard.record_details': '记录详情',
    'dashboard.within_healthy_range': '在健康范围内',
    'health_circle.delete_confirm_title': '确认删除',
    'settings.add_reminder': '添加提醒',
    'chat.ai_extracted_notes': 'AI 从聊天中提取：{text}',
    'community.post_type_tip': '贴士',
    'community.post_type_milestone': '里程碑',
    'settings.section_account': '账户',
    'settings.label_profile': '个人资料',
    'settings.label_role': '角色',
    'settings.label_privacy': '隐私',
    'settings.section_care_network': '护理网络',
    'settings.label_link_patient': '关联患者',
    'settings.status_linked': '已关联',
    'settings.status_not_linked': '未关联',
    'settings.main_caregiver_title': '主要护理人员',
    'settings.main_caregiver_desc': '选择紧急情况下的主要联系人。',
    'settings.label_my_caregivers': '我的护理人员',
    'settings.status_none': '无',
    'settings.section_health_services': '健康服务',
    'settings.label_emergency_location': '紧急位置',
    'settings.status_active': '活跃',
    'settings.status_disabled': '已禁用',
    'settings.label_wearable': '可穿戴设备集成',
    'settings.status_syncing': '同步中...',
    'settings.status_fitbit_connected': 'Fitbit 已连接',
    'settings.status_not_connected': '未连接',
    'settings.section_preferences': '偏好',
    'settings.label_smart_notifications': '智能通知',
    'settings.notifications_enabled_title': '通知已启用',
    'settings.notifications_enabled_body': '您现在将收到健康提醒和警报。',
    'settings.confirm_role_caregiver': '您确定要将角色更改为护理人员吗？您将能够监测关联的患者。',
    'settings.confirm_role_patient': '您确定要将角色更改为患者吗？您将能够监测自己的健康状况。',
    'settings.patient_id_not_found': '未找到患者 ID。',
    'settings.not_a_patient': '提供的 ID 不属于患者。',
    'settings.fitbit_connect_error': '连接 Fitbit 失败。请重试。',
    'settings.fitbit_sync_success': 'Fitbit 数据同步成功！',
    'settings.fitbit_sync_error': '同步 Fitbit 数据失败。',
    'settings.synced_from_fitbit': '从 Fitbit 同步',
    'settings.clinical_id_title': '临床身份卡',
    'settings.clinical_id_desc': '这张虚拟身份证可以轻松与您的看护人共享临床信息。',
    'settings.view_id_card': '查看身份证',
    'settings.copy_id': '复制 ID',
    'settings.id_copied': 'ID 已复制到剪贴板！',
    'settings.invite_token': '邀请码',
    'settings.refresh_token': '刷新',
    'settings.expires_in': '有效期剩余',
    'settings.no_active_token': '无激活的邀请码',
    'settings.generate_now': '立即生成',
    'settings.linkage_tip': '将此代码和您的患者 ID 分享给您的护理人员以绑定账户。',
    'settings.invite_token_label': '邀请码',
    'settings.link_account': '绑定账户',
    'settings.linkage_help': '请患者打开其个人资料 ID 卡以查看其 ID 和临时邀请码。',
    'settings.invalid_token': '邀请码无效',
    'settings.token_expired': '邀请码已过期',
    'settings.blood_type': '血型',
    'settings.allergies': '过敏',
    'settings.emergency_contact': '紧急情况',
    'settings.full_id': '完整 ID',
    'wearables.header_tagline': '设备集成',
    'wearables.header_title': '智能手表中心',
    'wearables.header_desc': '将您喜爱的可穿戴设备连接到 AIHMs，实现无缝、实时的健康监测。',
    'wearables.header_desc_caregiver': '管理 {name} 的可穿戴设备。同步生命体征和健康数据以监测他们的健康状况。',
    'wearables.connect_fitbit': '连接 Fitbit',
    'wearables.connect_apple': '连接 Apple Health',
    'wearables.connect_google': '连接 Google Fit',
    'wearables.sync_now': '立即同步',
    'wearables.simulate_sync': '模拟同步 (演示)',
    'wearables.coming_soon': 'Web 版即将推出',
    'wearables.steps_desc': '跟踪您的日常活动和目标。',
    'wearables.heart_desc': '实时静息心率监测。',
    'wearables.sleep_desc': '分析您的恢复和睡眠周期。',
    'community.task_morning_walk': '每日晨练',
    'community.task_recipe_share': '健康食谱分享',
    'community.task_group_chat': '每周群聊',
    'language.ms': '马来语 (Bahasa Melayu)',
    'language.en': '英语 (English)',
    'language.zh': '中文 (Mandarin)',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { profile, user } = useFirebase();
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    if (profile?.language) {
      setLanguageState(profile.language);
    }
  }, [profile?.language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string, params?: Record<string, any>): string => {
    let text = translations[language][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useTranslation must be used within LanguageProvider');
  return context;
};
